# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20ae26b2a049650b2c7914a0356533ba76e37181f93bfc725fc50991910735a23bbcc9ad31dc6d16ca1b2c8ae079d9a52b8b9d0b350287d71f6e468c60ab2cef

test:
  secret_key_base: 9ff671d81ecc7a3ffd6be54b07b5ec57cefc131a204bb8ec027cefdbc4090286b4462f2a3519e4388f956522e7ccc3b3a208b35335a573f12e14d6d38c4cdfeb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
